#pragma once
typedef __int64 (*GET_AUDIO_BUFFER_AND_SET_SIZE)(__int64*, byte**, int);
typedef __int64 (*TRANSFER_MIXED_AUDIO_TO_SOUND_BUFFER)(__int64*);

GET_AUDIO_BUFFER_AND_SET_SIZE hook1;
TRANSFER_MIXED_AUDIO_TO_SOUND_BUFFER hook2;

void SetupHooks(PVOID driver, GET_AUDIO_BUFFER_AND_SET_SIZE callback1, TRANSFER_MIXED_AUDIO_TO_SOUND_BUFFER callback2)
{
	byte* DS_CONTAINER = (byte*)driver + 0x20;
	byte* DIRECTSOUNDCOM = (byte*) * (__int64**)(DS_CONTAINER + 0x40);

	hook1 = *(GET_AUDIO_BUFFER_AND_SET_SIZE*)(DIRECTSOUNDCOM + 0x30);
	*(GET_AUDIO_BUFFER_AND_SET_SIZE*)(DIRECTSOUNDCOM + 0x30) = callback1;

	hook2 = *(TRANSFER_MIXED_AUDIO_TO_SOUND_BUFFER*)(DIRECTSOUNDCOM + 0x38);
	*(TRANSFER_MIXED_AUDIO_TO_SOUND_BUFFER*)(DIRECTSOUNDCOM + 0x38) = callback2;
}
